### ISSUE TITLE
status of this proposal

### ISSUE THREAD

**Issue by mheiber** [tschneidereit/proposal-typed-objects#7]
Is this proposal active?
If not, is it superseded by another proposal for typed objects?

Thanks for your help!

**Comment by tschneidereit** [comment]
It is active, yes! I know it doesn't look like it, but that's because we want to make sure that this proposal is well aligned with the [WebAssembly GC proposal](https://github.com/WebAssembly/gc/), so we're currently waiting for that to be a bit further along.
